#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

LOG_DIR="${REPO_ROOT}/logs"
mkdir -p "${LOG_DIR}"
mkdir -p "${REPO_ROOT}/data/whatsapp-gateway/session"

log() {
  printf '[start_clean] %s\n' "$*" >&2
}

warn() {
  printf '[start_clean][XƏBƏRDARLIQ] %s\n' "$*" >&2
}

fatal() {
  printf '[start_clean][XƏTA] %s\n' "$*" >&2
  exit 1
}

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    fatal "'$1' tapılmadı. Zəhmət olmasa quraşdırın."
  fi
}

require_cmd docker
require_cmd curl
require_cmd python3

if ! docker compose version >/dev/null 2>&1; then
  fatal "Docker Compose v2 tələb olunur (docker compose)."
fi

if [ -f "$REPO_ROOT/.env" ]; then
  log ".env faylı tapıldı, port dəyişənləri yüklənir."
  # shellcheck disable=SC1090
  set -a
  source "$REPO_ROOT/.env"
  set +a
else
  warn ".env faylı tapılmadı, default dəyərlər istifadə olunacaq."
fi

ensure_env_default() {
  local var_name="$1"
  local default_value="$2"
  if [[ -z "${!var_name:-}" ]]; then
    eval "export ${var_name}='${default_value}'"
    warn "${var_name} təyin edilməmişdi, default ${default_value} istifadə olunur."
  else
    export "${var_name?}"
  fi
}

ensure_env_default "WHATSAPP_GATEWAY_SESSION" "default"
ensure_env_default "WHATSAPP_GATEWAY_BASE_URL" "http://wweb:3001"
ensure_env_default "WHATSAPP_GATEWAY_HOST_URL" "http://localhost:3001"
ensure_env_default "WHATSAPP_GATEWAY_WEBHOOK_URL" "http://app:3000/webhook"
ensure_env_default "WHATSAPP_GATEWAY_WEBHOOK_EVENTS" "message,session.status"
ensure_env_default "APP_PORT" "3000"
ensure_env_default "WHATSAPP_GATEWAY_PORT" "3001"
ensure_env_default "DASHBOARD_PORT" "3002"
ensure_env_default "REDIS_PORT" "6379"
ensure_env_default "MCP_PORT" "3030"
ensure_env_default "POSTGRES_PORT" "55432"
ensure_env_default "REDIS_URL" "redis://redis:${REDIS_PORT}"
ensure_env_default "DATABASE_URL" "postgres://nexuscore:nexuscore@postgres:${POSTGRES_PORT}/nexuscore"
ensure_env_default "OPENAI_MODEL" "gpt-5.1"
ensure_env_default "OPENAI_VISION_MODEL" "gpt-4o"
ensure_env_default "OPENAI_TRANSCRIPTION_MODEL" "gpt-4o-mini-transcribe"
ensure_env_default "OPENAI_TTS_MODEL" "gpt-4o-mini-tts"
ensure_env_default "OPENAI_ROUTER_MODEL" "gpt-5-nano"
ensure_env_default "AGENT_MODEL_GENERAL" "gpt-5.1"
ensure_env_default "AGENT_MODEL_SALES" "gpt-5-mini"
ensure_env_default "AGENT_MODEL_SUPPORT" "gpt-4.1-mini"
ensure_env_default "AGENT_MODEL_DIAGNOSTICS" "gpt-4o"

write_backend_env_snapshot() {
  local output="${REPO_ROOT}/backend/.env.start_clean"
  cat > "${output}" <<EOF
# Generated by scripts/start_clean.sh on $(date)
DATABASE_URL=${DATABASE_URL}
REDIS_URL=${REDIS_URL}
WHATSAPP_GATEWAY_BASE_URL=${WHATSAPP_GATEWAY_BASE_URL}
WHATSAPP_GATEWAY_HOST_URL=${WHATSAPP_GATEWAY_HOST_URL}
WHATSAPP_GATEWAY_SESSION=${WHATSAPP_GATEWAY_SESSION}
APP_PORT=${APP_PORT}
WHATSAPP_GATEWAY_PORT=${WHATSAPP_GATEWAY_PORT}
DASHBOARD_PORT=${DASHBOARD_PORT}
MCP_PORT=${MCP_PORT}
OPENAI_API_KEY=${OPENAI_API_KEY:-}
GROQ_API_KEY=${GROQ_API_KEY:-}
EOF
  log "backend/.env.start_clean faylı yeniləndi. Lokal npm skriptləri üçün 'source backend/.env.start_clean' istifadə edə bilərsiniz."
}

write_backend_env_snapshot

resolve_port() {
  local var="${1}"
  local default="${2}"
  local value="${!var-}"
  if [[ -z "${value}" ]]; then
    echo "${default}"
  else
    echo "${value}"
  fi
}

APP_PORT="$(resolve_port APP_PORT 3000)"
DASHBOARD_PORT="$(resolve_port DASHBOARD_PORT 3002)"
GATEWAY_PORT="$(resolve_port WHATSAPP_GATEWAY_PORT 3001)"
POSTGRES_PORT="$(resolve_port POSTGRES_PORT 55433)"
REDIS_PORT="$(resolve_port REDIS_PORT 6379)"
MCP_PORT="$(resolve_port MCP_PORT 3030)"

free_port() {
  local port="$1"
  local label="$2"

  if ! command -v lsof >/dev/null 2>&1; then
    warn "lsof quraşdırılmayıb, port yoxlamaq mümkün deyil."
    return
  fi

  while lsof -ti "tcp:${port}" >/dev/null 2>&1; do
    local pids
    pids="$(lsof -ti "tcp:${port}")"
    log "Port ${port} (${label}) istifadə olunur. PIDs: ${pids}"

    if [[ "${port}" == "${POSTGRES_PORT}" ]] && command -v systemctl >/dev/null 2>&1; then
      if systemctl is-active --quiet postgresql; then
        log "Sistem Postgres servisi dayandırılır..."
        sudo systemctl stop postgresql || true
      fi
    fi

    for pid in ${pids}; do
      if ps -p "${pid}" >/dev/null 2>&1; then
        kill "${pid}" || true
      fi
    done

    sleep 1

    if lsof -ti "tcp:${port}" >/dev/null 2>&1; then
      warn "Port ${port} hələ də məşğuldur, SIGKILL tətbiq olunur."
      for pid in $(lsof -ti "tcp:${port}"); do
        kill -9 "${pid}" || true
      done
      sleep 1
      if lsof -ti "tcp:${port}" >/dev/null 2>&1; then
        fatal "Port ${port} sərbəst buraxılmadı. Manual müdaxilə tələb olunur."
      fi
    fi
  done

  log "Port ${port} (${label}) boşdur."
}

wait_for_http() {
  local label="$1"
  local url="$2"
  shift 2 || true
  local args=("$@")

  for _ in {1..30}; do
    if curl -fsS "${args[@]}" "$url" >/dev/null; then
      log "${label} aktivdir (${url})."
      return 0
    fi
    sleep 2
  done

  fatal "${label} ${url} ünvanında cavab vermir."
}

start_mcp_dev() {
  local flag="${START_MCP_DEV:-true}"
  if [[ "${flag,,}" != "true" ]]; then
    log "MCP dev serveri atlanır (START_MCP_DEV=${flag})."
    return
  fi

  if pgrep -f "src/mcp/server.ts" >/dev/null 2>&1; then
    local pid
    pid="$(pgrep -f "src/mcp/server.ts" | tr '\n' ' ')"
    log "MCP dev server artıq işləyir (PID: ${pid})."
    return
  fi

  log "MCP dev server işə salınır..."
  (cd "${REPO_ROOT}/backend" && nohup npm run mcp:dev > "${LOG_DIR}/mcp-dev.log" 2>&1 &)
  sleep 1
  if pgrep -f "src/mcp/server.ts" >/dev/null 2>&1; then
    log "MCP dev server başladı (loqlar: ${LOG_DIR}/mcp-dev.log)."
  else
    warn "MCP dev server start alınmadı, ${LOG_DIR}/mcp-dev.log faylını yoxlayın."
  fi
}

fetch_session_json() {
  curl -fsS \
    "${WHATSAPP_GATEWAY_HOST_URL:-http://localhost:${GATEWAY_PORT}}/api/sessions/${WHATSAPP_GATEWAY_SESSION:-default}" || true
}

parse_json_field() {
  local json="$1"
  local field="$2"
  python3 - <<'PY' "$json" "$field"
import json, sys
try:
    data = json.loads(sys.argv[1])
    field = sys.argv[2]
    parts = field.split(".")
    for part in parts:
        if isinstance(data, list):
            data = data[0] if data else None
        elif isinstance(data, dict):
            data = data.get(part)
        else:
            data = None
        if data is None:
            break
    if isinstance(data, (dict, list)):
        print(json.dumps(data))
    elif data is None:
        print("")
    else:
        print(data)
except Exception:
    print("")
PY
}

print_qr_code() {
  local base_url="${WHATSAPP_GATEWAY_HOST_URL:-http://localhost:${GATEWAY_PORT}}"
  local session_name="${WHATSAPP_GATEWAY_SESSION:-default}"
  local response_tmp
  response_tmp="$(mktemp)"

  if ! curl -fsS "${base_url}/api/${session_name}/auth/qr" -o "${response_tmp}"; then
    warn "QR kodu əldə etmək mümkün olmadı."
    rm -f "${response_tmp}"
    return 1
  fi

  local qr_b64
  qr_b64="$(python3 - <<'PY' "${response_tmp}"
import json, sys, pathlib
try:
    payload = json.loads(pathlib.Path(sys.argv[1]).read_text())
except json.JSONDecodeError:
    print("")
    sys.exit(0)
qr = payload.get("qr")
if isinstance(qr, str):
    print(qr.strip())
PY
)"

  rm -f "${response_tmp}"

  if [[ -z "${qr_b64// }" ]]; then
    warn "QR cavabı gözlənilən formatda deyil."
    return 1
  fi

  local decoded="${qr_b64#data:image/png;base64,}"
  local qr_file="${LOG_DIR}/gateway_qr_$(date +%Y%m%d%H%M%S).png"
  if ! printf '%s' "${decoded}" | base64 -d > "${qr_file}" 2>/dev/null; then
    warn "QR base64 məlumatı deşifrə edilə bilmədi."
    rm -f "${qr_file}"
    return 1
  fi

  log "WhatsApp gateway QR kodu ${qr_file} faylına yazıldı. Telefonla skan edin."
  log "Base64 (clipboard üçün):"
  printf '%s\n' "${decoded}"
  echo
  log "PNG faylını açmaq üçün: xdg-open \"${qr_file}\""
  return 0
}

ensure_gateway_session() {
  local session status me qr_printed=0
  local base_url="${WHATSAPP_GATEWAY_HOST_URL:-http://localhost:${GATEWAY_PORT}}"
  local session_name="${WHATSAPP_GATEWAY_SESSION:-default}"

  log "WhatsApp gateway sessiyası (${session_name}) yoxlanılır..."

  for _ in {1..30}; do
    session="$(fetch_session_json)"
    if [[ -n "${session}" ]]; then
      break
    fi
    sleep 2
  done

  if [[ -z "${session}" ]]; then
    warn "Gateway sessiya məlumatı alınmadı."
    return
  fi

  status="$(parse_json_field "${session}" "status")"
  me="$(parse_json_field "${session}" "me.id")"

  if [[ "${status}" == "WORKING" && -n "${me}" ]]; then
    log "Gateway sessiyası artıq autentifikasiyadan keçib (id: ${me})."
    return
  fi

  log "Sessiyanın cari statusu: ${status:-bilinmir}. Start komandası göndərilir..."
  curl -fsS -X POST \
    "${base_url}/api/sessions/${session_name}/start" >/dev/null || true

  for _ in {1..60}; do
    session="$(fetch_session_json)"
    status="$(parse_json_field "${session}" "status")"
    me="$(parse_json_field "${session}" "me.id")"

    if [[ "${status}" == "WORKING" && -n "${me}" ]]; then
      log "Gateway sessiyası autentifikasiyadan keçdi (id: ${me})."
      return
    fi

    if [[ "${status}" == "SCAN_QR_CODE" && "${qr_printed}" -eq 0 ]]; then
      log "Sessiya QR skanı gözləyir."
      if print_qr_code; then
        qr_printed=1
        log "Telefonla QR kodunu skan etdikdən sonra bu skript statusu avtomatik izləyir."
      else
        warn "QR kodu əldə etmək mümkün olmadı. Gateway dashboard/log fayllarını yoxlayın."
        qr_printed=1
      fi
    fi

    sleep 5
  done

  warn "Gateway sessiyası gözlənilən müddətdə WORKING vəziyyətinə keçmədi. Zəhmət olmasa manual olaraq yoxlayın."
}

log "Mövcud Docker konteynerləri dayandırılır..."
docker compose down --remove-orphans >/dev/null 2>&1 || true

free_port "${POSTGRES_PORT}" "Postgres"
free_port "${REDIS_PORT}" "Redis"
free_port "${GATEWAY_PORT}" "WhatsApp gateway"
free_port "${APP_PORT}" "Backend"
free_port "${DASHBOARD_PORT}" "Dashboard"
free_port "${MCP_PORT}" "MCP"

log "Docker imicləri yenidən qurulur..."
docker compose build

log "Servislər ayağa qaldırılır (detached rejim)..."
docker compose up --build -d

BACKEND_URL="${BACKEND_URL:-http://localhost:${APP_PORT}}"
GATEWAY_URL="${WHATSAPP_GATEWAY_HOST_URL:-http://localhost:${GATEWAY_PORT}}"

wait_for_http "Backend" "${BACKEND_URL}/healthz"
wait_for_http "WhatsApp gateway" "${GATEWAY_URL}/api/server/status"

start_mcp_dev
ensure_gateway_session

log "Stack hazırdır."
log "Gateway API: ${GATEWAY_URL}"
log "Backend admin panel: http://localhost:${DASHBOARD_PORT}"
log "MCP endpoint: http://localhost:${MCP_PORT:-3030}/mcp"
docker logs -f nexuscore-wa-wweb-1 2>&1 | tee -a "$(pwd)/logs/nexuscore-wa-wweb-1.log"
